/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteRouteImport } from './routes/todos/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TodosIndexRouteImport } from './routes/todos/index'
import { Route as TodosAddRouteImport } from './routes/todos/add'
import { Route as TodosIdEditRouteImport } from './routes/todos/$id/edit'

const TodosRouteRoute = TodosRouteRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosIndexRoute = TodosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodosRouteRoute,
} as any)
const TodosAddRoute = TodosAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => TodosRouteRoute,
} as any)
const TodosIdEditRoute = TodosIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => TodosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todos': typeof TodosRouteRouteWithChildren
  '/todos/add': typeof TodosAddRoute
  '/todos/': typeof TodosIndexRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todos/add': typeof TodosAddRoute
  '/todos': typeof TodosIndexRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/todos': typeof TodosRouteRouteWithChildren
  '/todos/add': typeof TodosAddRoute
  '/todos/': typeof TodosIndexRoute
  '/todos/$id/edit': typeof TodosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todos' | '/todos/add' | '/todos/' | '/todos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todos/add' | '/todos' | '/todos/$id/edit'
  id: '__root__' | '/' | '/todos' | '/todos/add' | '/todos/' | '/todos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodosRouteRoute: typeof TodosRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos/': {
      id: '/todos/'
      path: '/'
      fullPath: '/todos/'
      preLoaderRoute: typeof TodosIndexRouteImport
      parentRoute: typeof TodosRouteRoute
    }
    '/todos/add': {
      id: '/todos/add'
      path: '/add'
      fullPath: '/todos/add'
      preLoaderRoute: typeof TodosAddRouteImport
      parentRoute: typeof TodosRouteRoute
    }
    '/todos/$id/edit': {
      id: '/todos/$id/edit'
      path: '/$id/edit'
      fullPath: '/todos/$id/edit'
      preLoaderRoute: typeof TodosIdEditRouteImport
      parentRoute: typeof TodosRouteRoute
    }
  }
}

interface TodosRouteRouteChildren {
  TodosAddRoute: typeof TodosAddRoute
  TodosIndexRoute: typeof TodosIndexRoute
  TodosIdEditRoute: typeof TodosIdEditRoute
}

const TodosRouteRouteChildren: TodosRouteRouteChildren = {
  TodosAddRoute: TodosAddRoute,
  TodosIndexRoute: TodosIndexRoute,
  TodosIdEditRoute: TodosIdEditRoute,
}

const TodosRouteRouteWithChildren = TodosRouteRoute._addFileChildren(
  TodosRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodosRouteRoute: TodosRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
